import Head from "next/head";

import NotFound from "../components/Notfound/Notfound";

const Notfound = () => {
  return (
    <>
      <Head>
        <title>Pratham Portfolio</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NotFound />
    </>
  );
};

export default Notfound;
