import About from "../components/about/aboutPage";
import Head from "next/head";

const Home = () => {
  return (
    <>
      <Head>
        <title>About | Pratham Portfolio</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <About />
    </>
  );
};

export default Home;
