import Head from "next/head";
import Homepage from "../components/homepage/homepage";

export default function Home() {
  return (
    <>
      <Head>
        <title>Pratham Portfolio</title>
        <meta name="description" content="Generated by create-t3-app" />
        <meta content="width=device-width, initial-scale=1" name="viewport" />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Homepage />
    </>
  );
}
